version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: brini-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - brini

  web:
    image: nginx:alpine
    container_name: brini-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - brini

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: brini-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dbbrini
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - brini

  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/amd64
    container_name: brini-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8081:80"
    networks:
      - brini

networks:
  brini:
    driver: bridge

volumes:
  dbdata:
    driver: local